#!/usr/bin/env bash

if [[ $LANG =~ ru_RU.UTF ]] ; then
    declare -A translations=(
    [There is no systemd-run systemctl in the system, without it it will not work]="В системе нет systemd-run systemctl, без этого работать не будет"
    [Usage: ./ryzenadj_helper_installer <command>

<commands>
  i|install : Installation
  u|uninstall : Deletes all files after installation

  WARNING: Superuser rights required]="Использовать: ./ryzenadj_helper_installer <команда>

<команды>
  i|install : Установка
  u|uninstall : Удалить все файлы после установки

  ВНИМАНИЕ: Требуются права суперпользователя"
    [Superuser rights are required]="Необходимы права суперпользователя"
    [sudo or doas not found!]="sudo or doas не найдены!"
    [default]="по умолчанию"
    [Enter the maximum TDP of the processor from the power cable in watts]="Введите максимальный TDP процессора от кабеля питания в ваттах"
    [Enter the maximum TDP of the processor from the battery in watts]="Введите максимальный TDP процессора от батареи в ваттах"
    [Enter the maximum allowed CPU temperature in Celsius (default 70)]="Введите максимально допустимую температуру процессора в градусах Цельсия (по умолчанию 70)"
    [Enter the maximum allowed APU temperature in Celsius (default 70)]="Введите максимально допустимую температуру APU в градусах Цельсия (по умолчанию 70)"
    [Enter the maximum TDP of the processor from the power cable in watts from a weak charge (default 25)]="Введите максимальный TDP процессора от кабеля питания в ваттах от слабой зарядки (по умолчанию 25)"
    [Enter which profile to use (vantage) after reboot or shutdown, this is necessary for the second system, for example Windows]="Введите, какой профиль (vantage) использовать после перезагрузки или выключения, это необходимо для второй системы, например Windows"
    [Available profiles: performance, balanced, low-power (balanced by default)]="Доступные профили: performance, balanced, low-power (по умолчанию balanced)"
    [Invalid argument used, exiting in 3 seconds]="Был использован неправильный аргумент, выход через 3 секунды"
    [Install the ryzen_smu kernel module? May improve compatibility with ryzenadj]="Установить модуль ядра ryzen_smu? Может улучшить совместимость работы с ryzenadj"
    [Select y/yes or n/no (default no)]="Выбор y/yes или n/no (по умолчанию no)"
    [Select y/yes or n/no (default yes)]="Выбор y/yes или n/no (по умолчанию yes)"
    [Add rtcwake to the system so that the device automatically turns off after a long sleep]="Добавить rtcwake в систему, чтобы устройство автоматически выключалось после длительного сна"
    [Similar to hibernation, but without saving the current session]="По аналогии с гибернацией, только без сохранения текущий сессии"
    [How long to turn off the device during long sleep in minutes (default 180)]="Через какой период времени устройство выключать во время длительного сна в минутах (по умолчанию 180)"
    [For help, please use './ryzenadj_helper_installer help']="Для получения справки используйте './ryzenadj_helper_installer help'"
    [Secureboot is enabled in the BIOS, before using this script you need to import the key for signing dkms modules for ryzen_smu in mokutil]="Secureboot включен в BIOS, перед использованием этого скрипта необходимо импортировать ключ для подписи модулей dkms для ryzen_smu в mokutil"
    [Reboot your device, import the key and run the script again]="Перезагрузите устройство, импортируйте ключ и снова запустите скрипт"
    [Secureboot is enabled in BIOS, /var/lib/dkms/mok.pub for signing dkms modules for ryzen_smu is missing, disable secureboot or add the key for signing dkms modules to mokutil]="Secureboot включен в BIOS, /var/lib/dkms/mok.pub для подписи модулей dkms для ryzen_smu отсутствует, отключите Secureboot или добавьте ключ для подписи модулей dkms в mokutil"
    [[You can use any password]]="Вы можете использовать любой пароль"
    )
else
    declare -A translations=(
    [There is no systemd-run systemctl in the system, without it it will not work]="There is no systemd-run systemctl in the system, without it it will not work"
    [Usage: ./ryzenadj_helper_installer <command>

<commands>
  i|install : Installation
  u|uninstall : Deletes all files after installation

  WARNING: Superuser rights required]="Usage: ./ryzenadj_helper_installer <command>

<commands>
  i|install : Installation
  u|uninstall : Deletes all files after installation

  WARNING: Superuser rights required"
    [Superuser rights are required]="Superuser rights are required"
    [sudo or doas not found!]="sudo or doas not found!"
    [default]="default"
    [Enter the maximum TDP of the processor from the power cable in watts]="Enter the maximum TDP of the processor from the power cable in watts"
    [Enter the maximum TDP of the processor from the battery in watts]="Enter the maximum TDP of the processor from the battery in watts"
    [Enter the maximum allowed CPU temperature in Celsius (default 70)]="Enter the maximum allowed CPU temperature in Celsius (default 70)"
    [Enter the maximum allowed APU temperature in Celsius (default 70)]="Enter the maximum allowed APU temperature in Celsius (default 70)"
    [Enter the maximum TDP of the processor from the power cable in watts from a weak charge (default 25)]="Enter the maximum TDP of the processor from the power cable in watts from a weak charge (default 25)"
    [Enter which profile to use (vantage) after reboot or shutdown, this is necessary for the second system, for example Windows]="Enter which profile to use (vantage) after reboot or shutdown, this is necessary for the second system, for example Windows"
    [Available profiles: performance, balanced, low-power (balanced by default)]="Available profiles: performance, balanced, low-power (balanced by default)"
    [Invalid argument used, exiting in 3 seconds]="Invalid argument used, exiting in 3 seconds"
    [Install the ryzen_smu kernel module? May improve compatibility with ryzenadj]="Install the ryzen_smu kernel module? May improve compatibility with ryzenadj?"
    [Select y/yes or n/no (default no)]="Select y/yes or n/no (default no)"
    [Select y/yes or n/no (default yes)]="Select y/yes or n/no (default yes)"
    [Add rtcwake to the system so that the device automatically turns off after a long sleep]="Add rtcwake to the system so that the device automatically turns off after a long sleep"
    [Similar to hibernation, but without saving the current session]="Similar to hibernation, but without saving the current session"
    [How long to turn off the device during long sleep in minutes (default 180)]="How long to turn off the device during long sleep in minutes (default 180)"
    [For help, please use './ryzenadj_helper_installer help']="For help, please use './ryzenadj_helper_installer help'"
    [Secureboot is enabled in the BIOS, before using this script you need to import the key for signing dkms modules for ryzen_smu in mokutil]="Secureboot is enabled in the BIOS, before using this script you need to import the key for signing dkms modules for ryzen_smu in mokutil"
    [Reboot your device, import the key and run the script again]="Reboot your device, import the key and run the script again"
    [Secureboot is enabled in BIOS, /var/lib/dkms/mok.pub for signing dkms modules for ryzen_smu is missing, disable secureboot or add the key for signing dkms modules to mokutil]="Secureboot is enabled in BIOS, /var/lib/dkms/mok.pub for signing dkms modules for ryzen_smu is missing, disable secureboot or add the key for signing dkms modules to mokutil"
    [[You can use any password]]="You can use any password"
    )
fi
